import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Header} from "./header";
import {Footer} from "../components/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
    <head />
      <body className="relative min-h-screen bg-black bg-gradient-to-tr from-zinc-900/50 to-zinc-700/30">
      {
      process.env.ENABLE_VERCEL_ANALYTICS ? <Analytics /> : null
      }

      <Header />

      <main className="min-h-[80vh]">{children}</main>

      <Footer />

      </body>
    </html>

  );
}
