import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Header} from "./header";
import {Footer} from "../components/footer";
import {Analytics} from "../components/analytics";
import {Providers} from "./providers";
import clsx from "clsx";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx(inter.className, 'dark')}>
    <head />
      <body className="relative min-h-screen bg-black bg-gradient-to-tr from-zinc-900/50 to-zinc-700/30">
      {
      process.env.ENABLE_VERCEL_ANALYTICS ? <Analytics /> : null
      }
        <Providers>

          <Header />

          <main className="min-h-[80vh]">{children}</main>

          <Footer />

        </Providers>
      </body>
    </html>

  );
}
